openapi: 3.0.0
info:
  title: DotaRankNExt API
  version: 1.0.0
  description: API for DotaRankNExt - Manage Dota 2 players with Steam authentication
servers:
  - url: http://localhost:5500
    description: Local development
  - url: https://inventory.cloudns.be
    description: Production server
paths:
  /dota:
    get:
      summary: API Health Check
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "DotaRankNExt backend - API running"
  /dota/auth/login:
    post:
      summary: Admin login with username/password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "admin"
                password:
                  type: string
                  example: "123"
              required: [username, password]
      responses:
        '200':
          description: JWT token for admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Missing credentials
        '401':
          description: Invalid credentials
  /dota/auth/steam:
    get:
      summary: Initiate Steam login (redirects to Steam)
      tags:
        - Authentication
      description: Redirects user to Steam OpenID authentication page
      responses:
        '302':
          description: Redirect to Steam login
  /dota/auth/steam/return:
    get:
      summary: Steam authentication callback
      tags:
        - Authentication
      description: Steam redirects here after authentication. Returns JWT and redirects to frontend
      responses:
        '302':
          description: Redirect to frontend with token
          headers:
            Location:
              schema:
                type: string
                example: "http://localhost:3000/auth/callback?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  /dota/players:
    get:
      summary: List all players
      tags:
        - Players
      description: Get all players from database (no authentication required, no automatic update)
      responses:
        '200':
          description: List of players from DB
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 10
                  players:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        steam_id:
                          type: string
                          example: "76561198000000000"
                        name:
                          type: string
                          example: "Player Name"
                        dotabuff:
                          type: string
                          example: "https://www.dotabuff.com/players/123456"
                        mmr_estimate:
                          type: integer
                          nullable: true
                          example: 5000
                        rank_tier:
                          type: integer
                          nullable: true
                          example: 75
                        profile:
                          type: string
                          nullable: true
                          example: "Steam Profile Name"
                        avatar:
                          type: string
                          nullable: true
                          example: "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/..."
                        last_update:
                          type: integer
                          example: 1733011200000
    post:
      summary: Add or update a single player (Admin only)
      tags:
        - Players
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                steam_id:
                  type: string
                  example: "76561198000000000"
                name:
                  type: string
                  example: "Player Name"
                dotabuff:
                  type: string
                  example: "https://www.dotabuff.com/players/123456"
              required: [steam_id]
      responses:
        '200':
          description: Player added/updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Player agregado/actualizado"
                  player:
                    type: object
        '400':
          description: Missing steam_id
        '401':
          description: Unauthorized - invalid or missing token
        '500':
          description: Database error
  /dota/players/import:
    post:
      summary: Import multiple players from Excel file (Admin only)
      tags:
        - Players
      security:
        - bearerAuth: []
      description: |
        Upload an Excel file to bulk import players. 
        Required columns (case-insensitive):
        - ID or SteamID: Steam 64-bit ID
        - JUGADOR or player or name: Player name
        - Dotabuff: Link to Dotabuff profile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Excel file (.xlsx or .xls)
      responses:
        '200':
          description: Players imported successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 25
                  processed:
                    type: array
                    items:
                      type: object
        '400':
          description: Missing file
        '401':
          description: Unauthorized
        '500':
          description: Error processing Excel file
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
